// <auto-generated />
using System;
using EttvAPI.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EttvAPI.Data.Migrations
{
    [DbContext(typeof(EttvDbContext))]
    [Migration("20190628100259_addingSrcUriAndSrcExtention")]
    partial class addingSrcUriAndSrcExtention
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EttvAPI.Data.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<byte[]>("HashPassword")
                        .IsRequired()
                        .HasColumnType("binary(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("ProfileId");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("EttvAPI.Data.Models.ChannelProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserId");

                    b.Property<DateTime>("EndTime");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("StartTime");

                    b.Property<string>("VideoContentVideoId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("VideoContentVideoId");

                    b.ToTable("ChannelProgram");
                });

            modelBuilder.Entity("EttvAPI.Data.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Profile");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Volunteer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "N/A"
                        });
                });

            modelBuilder.Entity("EttvAPI.Data.Models.VideoContent", b =>
                {
                    b.Property<string>("VideoId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AppUserId");

                    b.Property<int>("Duration");

                    b.Property<string>("SrcExtention")
                        .IsRequired();

                    b.Property<string>("SrcUri")
                        .IsRequired();

                    b.Property<string>("Tag")
                        .IsRequired();

                    b.Property<string>("Thumbnail")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("VideoId");

                    b.HasIndex("AppUserId");

                    b.ToTable("VideoContent");
                });

            modelBuilder.Entity("EttvAPI.Data.Models.AppUser", b =>
                {
                    b.HasOne("EttvAPI.Data.Models.Profile", "Profile")
                        .WithMany("AppUsers")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EttvAPI.Data.Models.ChannelProgram", b =>
                {
                    b.HasOne("EttvAPI.Data.Models.AppUser", "AppUser")
                        .WithMany("ChannelPrograms")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EttvAPI.Data.Models.VideoContent", "VideoContent")
                        .WithMany("ChannelPrograms")
                        .HasForeignKey("VideoContentVideoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EttvAPI.Data.Models.VideoContent", b =>
                {
                    b.HasOne("EttvAPI.Data.Models.AppUser", "AppUser")
                        .WithMany("VideoContents")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
